//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppleStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loai_San_Pham
    {
        public Loai_San_Pham()
        {
            this.San_Pham = new HashSet<San_Pham>();
        }
    
        public int id { get; set; }
        public string tenloaiSP { get; set; }
    
        public virtual ICollection<San_Pham> San_Pham { get; set; }
    }
}
