//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppleStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class San_Pham
    {
        public San_Pham()
        {
            this.Chi_Tiet_Don_Hang = new HashSet<Chi_Tiet_Don_Hang>();
        }
        
        public int id { get; set; }
        [Display(Name = "Ten San Pham")]
        public string tenSP { get; set; }
        [Display(Name = "Hinh Anh")]
        public string hinh { get; set; }
        [Display(Name = "Gia")]
        public Nullable<double> gia { get; set; }
        [Display(Name = "Mo Ta")]
        public string mota { get; set; }
        [Display(Name = "Trang Thai")]
        public Nullable<bool> trangthai { get; set; }
        [Display(Name = "Ngay Dang Hinh ")]
        public Nullable<System.DateTime> ngaydanghinh { get; set; }
        [Display(Name = "Ten Loai San Pham")]
        public int idloaiSP { get; set; }
    
        public virtual ICollection<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hang { get; set; }
        public virtual Loai_San_Pham Loai_San_Pham { get; set; }
    }
}
