//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppleStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trang_Thai
    {
        public Trang_Thai()
        {
            this.Don_Hang = new HashSet<Don_Hang>();
        }
    
        public int id { get; set; }
        public string trangthai { get; set; }
    
        public virtual ICollection<Don_Hang> Don_Hang { get; set; }
    }
}
